### ISSUE TITLE
online dictionary helper extension support

### ISSUE THREAD

**Issue by ledvip** [KamWithK/AnkiconnectAndroid#1]
This Ankiconnect Android apk is amazing .Beside yomichan,there is another extension which is  simple and easy use,open for multiple languages  :online dictionary helper (https://chrome.google.com/webstore/detail/online-dictionary-helper/lppjdajkacanlmpbbcdkccjkdbpllajb?hl=en)  . It support Ankiconnect to localhost ,if this apk can have minor fix to support that extension ,that will definately have more and popular use.Thanks in advance!

**Comment by ledvip** [comment]
is it possible to provide http get and post ,just like computer version ankiconnect .When start android ankiconnect and browse 127.0.0.1:8765 get error: java.lang.NullPointerException : Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

**Comment by KamWithK** [comment]
That error is expected, I handle the commonly used Ankiconnect API calls by Yomichan and also support Forvo audio
For this reason (supporting 2 APIs on on port) I have to handle them both at the same time so I decide based on the parameters and all which was actually called
Henceforth, when you navigate to that page you get an error because that isn't actually a known query and maps to the wrong part of the code (Yomichan won't send something like that)

It's quite likely that when you actually try out your extension that it'll just work as-is, but if not then let me know what's going wrong and I'll take a look at what I can do about it

**Comment by ledvip** [comment]
Maybe a simple solution is to add a new project AnkiConnectAndroid2, which can provide standard 127.0.0.1:8765 connection just like computer version .

**Comment by KamWithK** [comment]
This project already provides an Android implementation of core Ankiconnect APIs (on an as-needed basis, determined by common Yomichan usage)
Although designed for Yomichan specifically it should relatively easily be usable by another project which makes these desktop Ankiconnect requests

**Comment by KamWithK** [comment]
> Maybe a simple solution is to add a new project AnkiConnectAndroid2, which can provide standard 127.0.0.1:8765 connection just like computer version .


If it's a particular API which hasn't yet been implemented but you want then please open a new issue for those describing their use case along and I can either implement it myself (if it's easy or worth it myself), or can explain what is required to do so/how to go about it 😉

On the other hand if you are fundamental unsatisfied by how this project works (for example technology or approach wise), feel free to fork this repo and make it your own
I'm happy to link to your repo if you've done something different/useful based off this or approve a pull request 🥺

**Comment by KamWithK** [comment]
Btw for clarity, this project doesn't do anything Yomichan specific (excluding the Forvo server maybe)
It's all usable everywhere where these desktop Ankidroid APIs were used (with some reasonable constraints due to this being a small project)
