### ISSUE TITLE
Can't create an Anki card

### ISSUE THREAD

**Issue by JekiXD** [KamWithK/AnkiconnectAndroid#10]
Hi! 
In yomichan popup window there's no "+" sign to create an Anki card, even though yomichan says that he's connected to Anki.
It even has all the information about Anki decks and note types, so it's definitely connected.
If you go to the http://127.0.0.1:8765 it gives you the following error:

Error: java.lang.NullPoniterException : Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

Any ideas how to fix it? Thanks for help in advance.

**Comment by KamWithK** [comment]
That isn't something to be fixed, you can't just go to the URL in a browser (there are technical reasons I've explained in the past)
These errors are all configuration errors (which change from one person to the next)
Please follow the instructions on GitHub (it should work), often this happens when you import from an old Yomichan desktop version or something (nothing I can realistically do to fix it)
