### ISSUE TITLE
Same problems with duplicates check

### ISSUE THREAD

**Issue by Draighneys** [KamWithK/AnkiconnectAndroid#15]
Hi once again,

I still have the same issue with the duplicates card. It seems like there was a new release that should've fixed the problem but it didn't. I couldn't find you're discord on the readme. If you put you're discord in the readme I can send you the config json that I am using in yomichan on my phone with kiwi browser.
 
If I can manage to reach you, I would have some questions on the project and maybe I could fix it on my own if you don't see any issues with the setup etc..

Thanks in advance,

**Comment by KamWithK** [comment]
Issues with Ankiconnect Android are almost always due to your Yomichan config being bad, start from scratch and go through the steps one by one and it should all work out fine 😁 

I don't have my own Discord server for my tools but if you post on [The Moe Way]( https://learnjapanese.moe/join/) and @ me I will respond 👍
