### ISSUE TITLE
Yomichan add expression button greyed out

### ISSUE THREAD

**Issue by larkalfen04** [KamWithK/AnkiconnectAndroid#21]
Yomichan status says it is **connected with Anki Integration** without any problem.
I can also use Yomichan in Kiwi Browser and have configured the card format.

But the **add expression button is greyed out** regardless.
Help for guidance. _(Anyways I cannot find your discord user)_

**Comment by Aquafina-water-bottle** [comment]
Under `Yomichan settings` -> `Anki` -> `Configure Anki card format…`, can you make sure that neither of the deck / model sections have a red box around them?
![image](https://user-images.githubusercontent.com/17107540/217664487-01c616a6-241f-486f-975f-cf4dbf0af328.png)

**Comment by larkalfen04** [comment]
![Screenshot_2023-02-09-06-47-44-92_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/117067259/217677763-22f1db85-b01a-448a-8181-e2d5db29a019.jpg)
Here is mine.

**Comment by Aquafina-water-bottle** [comment]
I'm not too sure then, maybe @KamWithK would know? The only other thing I can think of is reset your Yomichan settings and try again from scratch.

This should be unrelated, but as a sanity check: do any of your field names have spaces? There may be a potential bug where if the first field name has a space, the query may not work since [the query itself isn't quoted](https://github.com/KamWithK/AnkiconnectAndroid/blob/master/app/src/main/java/com/kamwithk/ankiconnectandroid/ankidroid_api/NoteAPI.java#L47).

**Comment by larkalfen04** [comment]
**Problem solved.** Here is my case.
Sometimes scrolling become hard because everytime my finger moves, it opens Yomichan panel. So I disabled (enable content scanning in General tab). I mainly use Yomichan search page on mobile.

Just now I fiddle with Yomichan settings as you suggest. **Turns out it seems enable content scanning is necessary.**
Now I can add card to Anki deck. Thanks!

**Comment by Aquafina-water-bottle** [comment]
Awesome, glad it's fixed!

One quick note:
> Sometimes scrolling become hard because everytime my finger moves, it opens Yomichan panel.

Can you try following the instructions [here](https://github.com/Aquafina-water-bottle/AnkiconnectAndroid/tree/local_audio#instructions) (specifically step 5)? It personally solved the problem on my device, and the Yomichan panel no longer opens when scrolling.

**Comment by larkalfen04** [comment]
Yes it solved the scroll. Your help rly means a lot for me. Thanks 🙏
