### ISSUE TITLE
Request from Kiwi Browser to AnkiConnect only goes through when switching out of Kiwi

### ISSUE THREAD

**Issue by bryangarza** [KamWithK/AnkiconnectAndroid#4]
Most of the time, when doing lookups, the Yomichan popup shows the loading bar on top indefinitely until I switch out of Kiwi (going to the home screen or another app). Once I do that, the request goes through and the Plus button shows up in the Yomichan popup.

I have battery optimization disabled for AnkiConnect, AnkiDroid, and Kiwi. I also “locked” each of them in the app switcher.

Device: OnePlus 9
Android version: 12

This might be OnePlus-specific — apparently it’s notorious for killing background apps. https://dontkillmyapp.com/oneplus

But the weird thing is that Kiwi itself seems to be the one having issues sending (or completing?) the request. Also, as far as I can tell, AnkiConnect itself is active.

I can provide any other info, just let me know.

Also glad to contribute a patch if needed, though I might need some hand-holding, as I haven’t written any Android code before.

**Comment by bryangarza** [comment]
A couple more observations:

- When I disable “Check for card duplicates”, the issue happens less often
- My current theory is that the API calls to AnkiConnect are hanging, and leaving Kiwi Browser kills the API calls, making Yomichan “complete” the requests

**Comment by bryangarza** [comment]
If I click to create a card and that hangs, leaving Kiwi also makes it go through.

**Comment by bryangarza** [comment]
Seems that enabling the “Allow background activity” setting for Kiwi, AnkiConnect, and AnkiDroid might have solved things. It’s a per-app setting within the Battery menu. I need to do some more testing with it but I will report back in a day or two.

**Comment by KamWithK** [comment]
I've had messages numerous people use Ankiconnect Android and the effect of doing things like disabling battery optimizations seems to vary dramatically. Some people need to enable options like these to have it work at all, for some people it works no matter what and for others it just extends usage time so this isn't 100% surprising to me.

I'm not sure why the requests would "hang" (I know what you mean though) when duplicates are being checked. These queries would definitely take a little longer (since they have to go through the Ankidroid API) but it shouldn't be bad enough to cause hanging.
Most users seem fine but I've had one other person describe it hanging (and I experienced this once). This only seems to happen when you mine *almost every single word you see* and in an hour or so you'd have massive slowdowns (which go away after restarting). Overall a bug like this which 99.99% of people never experience is probably not worth extensive testing imo (although I do want to look into my Forvo api's effect on this, I have a feeling that when the word doesn't exist it might hang).

I am though interested in your experience so I'll leave this open for a bit more in-case you want to update me on what you think causes the hanging or anything else :)

**Comment by bryangarza** [comment]
Thanks for your detailed response :)

After enabling "Allow background activity" and reading for more than an hour, I didn't face the issue anymore.

I did have an idea of something that could be potentially useful in the future in case someone runs into a similar situation. Perhaps if AnkiConnect had some sort of "debug" mode that could be turned on to log incoming requests and their responses, and perhaps even display notifications for these. Then it would be easier to tell where the delay is coming from. This is probably low priority though cause as you said, it's not a common issue (I can create one though if you'd like).

I'll put up a PR to update the README with what I did to solve my issue in case anyone runs into it, that should be enough for now.

**Comment by KamWithK** [comment]
If you're able you can install Android Studio and clone this project
You can insert some logs to the terminal and see how far they get before they're terminated or whatever (when allow run in background is off)
Pretty sure though that it's fine as is
When Android stops background activity the requests just won't even reach though as far as I know (should take around a few mins before it stops working, so then you wouldn't have anything logged)
