### ISSUE TITLE
FR: Connecting to Koreader

### ISSUE THREAD

**Issue by unacceptablet** [KamWithK/AnkiconnectAndroid#47]
Greetings!

My device: Onyx Boox Leaf 2 (android 11)

I have installed a Koreader plugin using this tutorial guide: https://github.com/Ajatt-Tools/anki.koplugin
Then I installed [AnkiconnectAndroid](https://github.com/KamWithK/AnkiconnectAndroid), put http://localhost:8765/ in CORS Host settings, start service. When I press add to anki in Koreader, I get these errors:

![image](https://github.com/KamWithK/AnkiconnectAndroid/assets/127971612/670e6f6c-5830-43e6-a30b-dbcced961390)

Any solutions?

**Comment by KamWithK** [comment]
I've never tried to use CORS nor KOreader with Ankiconnect Android before personally, so maybe @Aquafina-water-bottle you would have a better idea of what could be going wrong?

**Comment by Twinov** [comment]
Read the error message and looked at the code, right now the parser has
`.get("audio").getAsJsonArray();`
but looks like this request is a single object and not an array. According to https://github.com/FooSoft/anki-connect#addnote it's a valid request, but I have a feeling #43 might fix this (or at least that should go in first and then fix applied after if not)

Sorry I haven't gotten around to looking at it, I'll look at #43 soon 😅

**Comment by Bluemoondragon07** [comment]
I spent hours trying to do the exact same thing on my Meebook M7 and got the exact same errors. Found a workaround yet?

**Comment by Bluemoondragon07** [comment]
Different errors now, actually. 

```
2 note(s) failed to sync:
- Couldn't get deck IDjava.lang.Exception: Couldn't get deck ID
at
com.kamwithk.ankiconnectandroid.ankidroid_api.DeckAPI.getDeckID(DeckAPI.java:50)
at
com.kamwithk.ankiconnectandroid.ankidroid_api.IntegratedAPI.addNote(IntegratedAPI.java:150)
at
```
...and so on and so forth. I'll attach a screenshot once I find out how to do so on this device.

**Comment by nairyosangha** [comment]
> Different errors now, actually.
> 
> ```
> 2 note(s) failed to sync:
> - Couldn't get deck IDjava.lang.Exception: Couldn't get deck ID
> at
> com.kamwithk.ankiconnectandroid.ankidroid_api.DeckAPI.getDeckID(DeckAPI.java:50)
> at
> com.kamwithk.ankiconnectandroid.ankidroid_api.IntegratedAPI.addNote(IntegratedAPI.java:150)
> at
> ```
> 
> ...and so on and so forth. I'll attach a screenshot once I find out how to do so on this device.

Hey, I don't think this is an error, or at least not something wrong with this Ankiconnect implementation. It's showing an error because it couldn't map whatever deck name you gave it to a deck id, so that name is probably just wrong on your end.

These errors could be clearer though IMO, it's a bit strange to get a 'Couldn't get deck ID' when trying to add a card, would be more clear if it just told you it couldn't find the deck with name X. And maybe you don't really need the whole stacktrace in the error :smile: although it was helpful to check

As far as I can tell this issue can be closed because it indeed looks like the new implentation handles the singular 'audio' object fine now
