### ISSUE TITLE
Duplicate checking does not match ankiconnect

### ISSUE THREAD

**Issue by Kuuuube** [KamWithK/AnkiconnectAndroid#61]
Currently, yomitan's duplicate checking is running into some issues due to inconsistencies between ankiconnect and ankiconnect android.

This is not related to previous yomitan issues due to ankiconnect android missing parts of ankiconnect's api but instead how it returns data.

Related yomitan issue https://github.com/themoeway/yomitan/issues/835

**Comment by drakargx** [comment]
Believe this is due to ankiconnect android's implementation of canAddNotes, it doesn't check for if "allowDuplicates" is true or false and just always assumes it's set to false. When https://github.com/themoeway/yomitan/issues/818, the duplicate add button was implemented by comparing the list of notes that can be added with and without allowing duplicates, so Ankiconnect android will just produce equal lists (if a note is in both lists, it is marked as "allowed, but not a duplicate").

Will need to respect the allowDuplicate flag, perhaps it is also worth supporting the full list of options too.

**Comment by drakargx** [comment]
For now I believe I've resolved this issue in this branch https://github.com/drakargx/AnkiconnectAndroid/releases/tag/prelims

Needs further testing and definitely needs code changes but I won't be able to take care of anything else until 4/21 at earliest.

**Comment by KamWithK** [comment]
> For now I believe I've resolved this issue in this branch https://github.com/drakargx/AnkiconnectAndroid/releases/tag/prelims
> 
> Needs further testing and definitely needs code changes but I won't be able to take care of anything else until 4/21 at earliest.

If that's the case #60 when it is ready should resolve this so we'll wait on you, no hurry

**Comment by drakargx** [comment]
> > For now I believe I've resolved this issue in this branch https://github.com/drakargx/AnkiconnectAndroid/releases/tag/prelims
> > Needs further testing and definitely needs code changes but I won't be able to take care of anything else until 4/21 at earliest.
> 
> If that's the case #60 when it is ready should resolve this so we'll wait on you, no hurry

https://github.com/KamWithK/AnkiconnectAndroid/pull/60 now has the changes implemented

**Comment by KamWithK** [comment]
> > > For now I believe I've resolved this issue in this branch https://github.com/drakargx/AnkiconnectAndroid/releases/tag/prelims
> > > Needs further testing and definitely needs code changes but I won't be able to take care of anything else until 4/21 at earliest.
> > 
> > 
> > If that's the case #60 when it is ready should resolve this so we'll wait on you, no hurry
> 
> #60 now has the changes implemented

I'll take a look today or tomorrow

**Comment by akacoda1** [comment]
Bump! 
this still remains a issue

**Comment by KamWithK** [comment]
#60 is now merged which should fix this issue

If it does not then please reopen and comment saying so
