### ISSUE TITLE
Duplicates are not working for me

### ISSUE THREAD

**Issue by Draighneys** [KamWithK/AnkiconnectAndroid#8]
Duplicates are not working in my case. I can even add two times the exact same card within a second. Ankidroid and ankiweb are detecting the duplicates. I'm using furigana as the "primary key" for filtering. It works fine with desktop ankiconnect. I tested to change the primary key as a constant string and the problem still occurs. I think somehow android ankiconnect is not getting information that card is a duplicate.  Card is added instantly so there's no timeout or anything.

**Comment by KamWithK** [comment]
Duplicates won't be detected if you mine multiple words at the same time, this is a small weakness of the current implementation/code. To explain that a little more, if you mine a word, close the window and reopen it that word should be detected as a duplicate, however, if you open a new word window, mine one entry and then scroll down and mine another, even if they're the exact same they will both get mined.

I assume that's what you mean, otherwise I'm not entirely sure why it'd happen (you'd have to provide more details otherwise for me to be able to check). It could otherwise be a yomichan update-caused problem tho too...

**Comment by Draighneys** [comment]
Hi @KamWithK and thanks for the answer,

I don't really understand what you mean by "mine multiple words at the same time". In my case I just:

1. tap on one word in a sentence
2. click on the add button on yomichan to add in my deck 
3. tap away to make the popup disapear
4. tap on the exact same word with same definition. yomichan pops with the + sign still on as if it had never been added
5. tap to add it and no error is displayed.

The word I took as an example to test is a word already existing in my deck (before step 1).

**Comment by Xelieu** [comment]
I think there really is a separate issue about this @KamWithK , not only me but also others that I think I've been noticing since last month -- what I think I noticed tho is the icons are gone (+) for supposedly already existing cards, if that's the case that would be great but as I am only relying by memory, sometimes I doubt myself if a specific card already exists with those cards that has missing + icon (didn't double check I was lazy haha)

**Comment by KamWithK** [comment]
Hey Xelieu,

I have heard this been mentioned on TMW Discord recently by a few people
It seems like a pretty minor discrepancy which most people (including me) didn't notice though
Just as long as the majority of words get correctly identified as duplicate/not duplicate then I think Ankiconnect Android is working well enough
Anki is just a little extra spice ontop of core immersion after all

Please do create a GitHub issue detailing the problem with ~10 examples of it not working though
Once I have examples I can determine whether it's a small bug fix for me, an Ankidroid problem (which I think it might be), or something entirely different which requires significant effort
I might still work on fixing this eventually, especially if more people on the community reach out about it (might be worth creating a small poll on TMW Discord to see how many people feel like they might've been affected)

I am going to close this one since it's for something different which hasn't really been discussed in a while
(I'm willing to bet it was probably a config problem or something, iirc those happened often before and there was never anything I could do to fix them unfortunately)

**Comment by Aquafina-water-bottle** [comment]
@Xelieu @Draighneys I believe the bug is fixed now. Try using the latest version of AnkiconnectAndroid: https://github.com/KamWithK/AnkiconnectAndroid/releases/tag/1.6-beta (you likely have to remove the existing app and re-install the APK).
